### ISSUE TITLE
Commucation between simgo.processes

### ISSUE THREAD

**Issue by kenenbek** [bgmerrell/simgo#2]
Consider such situation when one `simgo.Process` wants to say something to another one. I supposed it can be done by passing a channel to function:
`func (s *someType) someFunction(env *simgo.Environment, pc *simgo.ProcComm) interface{}
`
but `someProcess.env.Run(nil)` doesn't have a `place` for channel. 

Do you have insights how it can be implemented?
Possibility to have interprocess communication is very helpful while modeling `master-slave` paradigm.

**Comment by bgmerrell** [comment]
Hi @kenenbek, thanks for your interest and question!
  Here is an example of a process returning a value to another: https://github.com/bgmerrell/simgo/blob/master/examples/multiple_procs.go

Does this accomplish what you had in mind?  If not, can you show me an example in Simpy of what you had in mind?  My goal right now is to achieve feature parity with Simpy.

**Comment by kenenbek** [comment]
Yes, it is good example. But I think this one is more suitable http://simpy.readthedocs.io/en/latest/examples/latency.html . But it requires `Store` class to be implemented.

**Comment by kenenbek** [comment]
Do you have some drafts or insights how `Store` can be implemented?

**Comment by bgmerrell** [comment]
@kenenbek I only have a tiny bit of code written for shared resources.  I am using the simpy code as an example, but the simpy code will need transformed a lot to be idiomatic Go code.  I don't think it will be very difficult, though.
